### PR TITLE
parser: Support statement 'SHOW PLACEMENT LABELS'

### PR DESCRIPTION
**Pull request by lcwangchao**
### What problem does this PR solve? 

Support statement 'SHOW PLACEMENT LABELS'

### What is changed and how it works?

Support statement 'SHOW PLACEMENT LABELS'

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
@morgo You could merge it if it looks good to you, too.

**Pull request merged**
