### PR TITLE
parser: rename 'timestampliteral' to avoid misuse of 'select timestampliteral()'

### PR DESCRIPTION
**Pull request by tiancaiamao**
### What problem does this PR solve? 

For https://github.com/pingcap/tidb/pull/12995

When the input is `select timestamp '2019-10-29 16:14:42'`, it's parsed to something like
    
`select timestampliteral('2019-10-29 16:14:42')`
    
`timestampliteral` is a valid function name in TiDB, used to implement the timestamp literal.
    
However, if the input is `select timestampliteral()`, we should reject this query.

### What is changed and how it works?

See parser.y

### Check List 

Tests 

 - No code

 - Need to be included in the release note

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @tangenta @SunRunAway

**Comment by kennytm** [comment]
Er this solution...

* it needs to reject `DATELITERAL` and `TIMELITERAL` too?
* and why is accepting the `TIMESTAMPLITERAL()` function a problem in the first place?

**Comment by tiancaiamao** [comment]
In mysql:

select timestampliteral(rand());
FUNCTION db_9_50fdf.timestampliteral does not exist

In TiDB:

select timestampliteral(rand());
```
github.com/pingcap/tidb/server.(*clientConn).Run.func1(0x2569c40, 0xc001124120, 0xc00029e0d0)
	github.com/pingcap/tidb@/server/conn.go:617 +0xee
panic(0x1fa2520, 0x250ff40)
	runtime/panic.go:679 +0x1b2
github.com/pingcap/tidb/expression.(*timestampLiteralFunctionClass).getFunction(0xc0002853a0, 0x25afca0, 0xc000e80000, 0xc0005214e0, 0x1, 0x1, 0x1, 0x1, 0xc00006b880, 0x7fba96becd98)
	github.com/pingcap/tidb@/expression/builtin_time.go:4509 +0x658
github.com/pingcap/tidb/expression.newFunctionImpl(0x25afca0, 0xc000e80000, 0xa3ea8801, 0xc001502b28, 0x10, 0xc000526b10, 0xc0005214d0, 0x1, 0x1, 0x0, ...)
	github.com/pingcap/tidb@/expression/scalar_function.go:137 +0x21d
github.com/pingcap/tidb/expression.NewFunction(...)
	github.com/pingcap/tidb@/expression/scalar_function.go:157
github.com/pingcap/tidb/planner/core.(*expressionRewriter).newFunction(0xc000725b80, 0xc001502b28, 0x10, 0xc000526b10, 0xc0005214d0, 0x1, 0x1, 0x40, 0x0, 0xc000725bb8, ...)
	github.com/pingcap/tidb@/planner/core/expression_rewriter.go:949 +0x13f
github.com/pingcap/tidb/planner/core.(*expressionRewriter).funcCallToExpression(0xc000725b80, 0xc000526b00)
	github.com/pingcap/tidb@/planner/core/expression_rewriter.go:1437 +0x20e
github.com/pingcap/tidb/planner/core.(*expressionRewriter).Leave(0xc000725b80, 0x256ac80, 0xc000526b00, 0x2582b80, 0xc000526a50, 0x1b07501)
	github.com/pingcap/tidb@/planner/core/expression_rewriter.go:871 +0xe62
github.com/pingcap/parser/ast.(*FuncCallExpr).Accept(0xc000526b00, 0x254c040, 0xc000725b80, 0xc00101e580, 0x1b07337, 0x0)
	github.com/pingcap/parser@v0.0.0-20191025082927-f8adf1670b97/ast/functions.go:457 +0x182
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteExprNode(0xc001235dc0, 0xc000725b80, 0x2582b80, 0xc000526b00, 0xc001398601, 0xc000725b80, 0x7fba96becd98, 0x0, 0xc000e80000, 0x0, ...)
	github.com/pingcap/tidb@/planner/core/expression_rewriter.go:139 +0x4e
github.com/pingcap/tidb/planner/core.(*PlanBuilder).rewriteWithPreprocess(0xc001235dc0, 0x2569c40, 0xc001124120, 0x2582b80, 0xc000526b00, 0x25af2c0, 0xc001398600, 0x0, 0x0, 0x1, ...)
	github.com/pingcap/tidb@/planner/core/expression_rewriter.go:109 +0x160
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildProjection(0xc001235dc0, 0x2569c40, 0xc001124120, 0x25af2c0, 0xc001398600, 0xc000010cb0, 0x1, 0x1, 0x0, 0x0, ...)
	github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:792 +0x586
github.com/pingcap/tidb/planner/core.(*PlanBuilder).buildSelect(0xc001235dc0, 0x2569c40, 0xc001124120, 0xc0013f2000, 0x25af2c0, 0xc001398600, 0x0, 0x0)
	github.com/pingcap/tidb@/planner/core/logical_plan_builder.go:2190 +0x503
github.com/pingcap/tidb/planner/core.(*PlanBuilder).Build(0xc001235dc0, 0x2569c40, 0xc001124120, 0x256b740, 0xc0013f2000, 0xc001235dc0, 0xc000e68528, 0xc0013f2000, 0xc0002de0b0)
	github.com/pingcap/tidb@/planner/core/planbuilder.go:377 +0xc07
github.com/pingcap/tidb/planner.optimize(0x2569c40, 0xc001124120, 0x25afca0, 0xc000e80000, 0x256b740, 0xc0013f2000, 0x258ba40, 0xc00045e7b0, 0xcd881b, 0xc000606000, ...)
	github.com/pingcap/tidb@/planner/optimize.go:76 +0x17f
github.com/pingcap/tidb/planner.Optimize(0x2569c40, 0xc001124120, 0x25afca0, 0xc000e80000, 0x256b740, 0xc0013f2000, 0x258ba40, 0xc00045e7b0, 0x0, 0x0, ...)
	github.com/pingcap/tidb@/planner/optimize.go:54 +0x1fa
github.com/pingcap/tidb/executor.(*Compiler).Compile(0xc00101efa8, 0x2569c40, 0xc001124120, 0x2570080, 0xc0013f2000, 0x0, 0x0, 0x0)
	github.com/pingcap/tidb@/executor/compiler.go:62 +0x247
github.com/pingcap/tidb/session.(*session).execute(0xc000e80000, 0x2569c40, 0xc001124120, 0xc001502b21, 0x1f, 0xd0865f, 0xc000058a00, 0xc00101f2b8, 0xd07ee7, 0xd4a855)
	github.com/pingcap/tidb@/session/session.go:1103 +0x5e7
github.com/pingcap/tidb/session.(*session).Execute(0xc000e80000, 0x2569c40, 0xc001124120, 0xc001502b21, 0x1f, 0x0, 0x0, 0x0, 0x0, 0x0)
	github.com/pingcap/tidb@/session/session.go:1056 +0xdb
github.com/pingcap/tidb/server.(*TiDBContext).Execute(0xc001124420, 0x2569c40, 0xc001124120, 0xc001502b21, 0x1f, 0x0, 0xc00065c001, 0x1, 0x0, 0x0
```

**Comment by kennytm** [comment]
In MySQL it says "`FUNCTION db_9_50fdf.timestampliteral does not exist`" only because you're in the database `db_9_50fdf`, and also that MySQL supports [UDFs](https://dev.mysql.com/doc/refman/5.7/en/create-function-udf.html). So rewriting `timestampliteral(…)` always to `db_9_85b2e2.timestampliteral(…)` doesn't make sense.

I think better solutions would be 

* Change `ast.TimestampLiteral` from `"timestampliteral"` to a name which is harder to conflict e.g. `"<tidb_native_timestamp>"`
* If we really wanna safe-guard it, produce a _parse_ error immediately when encountering function calls involving `ast.TimestampLiteral` and friends
* Or maybe don't reuse FuncCallExpr for these literals, and instead introduce a new kind of Expr or make these special types of ValueExpr

**Comment by tiancaiamao** [comment]
> Change ast.TimestampLiteral from "timestampliteral" to a name which is harder to conflict e.g. "<tidb_native_timestamp>"

Then we still need to handle `select(<tidb_native_timestamp>(rand()))` panic?

> produce a parse error immediately

MySQL doesn't treat it as a parser error

> Or maybe don't reuse FuncCallExpr for these literals, and instead introduce a new kind of Expr or make these special types of ValueExpr

That's good, but it involves much more work.

I'll choose method one, and use a strange function name that unlikely to conflict.

**Comment by tiancaiamao** [comment]
Done @kennytm 
I think the new function name is unlike (if possible) to conflict with a user's input.

**Comment by tiancaiamao** [comment]
Update Go1.13 first:
https://github.com/pingcap/parser/pull/593

Then the integration test would pass, and then merge this one: 
https://github.com/pingcap/tidb/pull/12995

**Comment by kennytm** [comment]
PTAL @tangenta

**Pull request merged**
