### PR TITLE
mysql: update sql-mode default

### PR DESCRIPTION
**Pull request by morgo**
Change TiDB to use the same default as MySQL 5.7

Depends on https://github.com/pingcap/tidb/pull/8278 (merged)

### CODE REVIEW

**Comment by morgo** [comment]
See also: https://github.com/pingcap/docs/pull/728 -- it turns out TiDB has great support for MySQL's SQL modes.  It just doesn't enable them all by default like mysql does :-)

**Comment by tiancaiamao** [comment]
LGTM @zimulala

**Comment by tiancaiamao** [comment]
Ping @zimulala

**Comment by zz-jason** [comment]
should we file a PR in TiDB to test this change? @morgo @tiancaiamao

**Comment by morgo** [comment]
@zz-jason The corresponding TiDB PR is https://github.com/pingcap/tidb/pull/8278

NO_ZERO_DATE did break the set suite, but it's since been fixed.

**Comment by tiancaiamao** [comment]
LGTM
PTAL @zz-jason @zimulala

**Pull request merged**
