### PR TITLE
parser : add error number for store limit error (#612)

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve? 
cherry-pick #612 to release-3.0

### What is changed and how it works?
add error number for store limit error in mysql package

### Check List 

Tests 

 - Manual test (add detailed scripts or steps below)

Release note
 - add error number for store limit error (#612)

### CODE REVIEW

**Comment by tangenta** [comment]
The error reported in CI says 
```
store/tikv/2pc.go:753:69: time.Since(lockWaitStartTime).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
```
The method `Milliseconds` of `Duration` is added go 1.13, it seems we need to set the go version to 1.13 in go.mod.

**Comment by AilinKid** [comment]
> The error reported in CI says
> 
> ```
> store/tikv/2pc.go:753:69: time.Since(lockWaitStartTime).Milliseconds undefined (type time.Duration has no field or method Milliseconds)
> ```
> 
> The method `Milliseconds` of `Duration` is added go 1.13, it seems we need to set the go version to 1.13 in go.mod.

Thanks very much, let me try it.

**Pull request merged**
