### PR TITLE
lexer: treat dot differently in different context

### PR DESCRIPTION
**Pull request by xiongjiwei**
### What problem does this PR solve? 

close https://github.com/pingcap/parser/issues/1114

related tidb issues: 
https://github.com/pingcap/tidb/issues/3963
https://github.com/pingcap/tidb/issues/21677

### What is changed and how it works?

`dot` after the identifier is token '.'
start with `dot` should be numbers

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Review by kennytm — COMMENTED** [review]
LGTM

**Review by breeswish — COMMENTED** [review]
Since https://github.com/pingcap/tidb/issues/21677 is related, could you also add unit tests for `select t.1e from test.t;`?

The rest LGTM, thanks!

**Comment by xiongjiwei** [comment]
> Since [pingcap/tidb#21677](https://github.com/pingcap/tidb/issues/21677) is related, could you also add unit tests for `select t.1e from test.t;`?

updated  PTAL

**Review by wjhuang2016 — COMMENTED** [review]
LGTM

**Pull request merged**
