### PR TITLE
Add bytebase/bytebase as a user

### PR DESCRIPTION
**Pull request by tianzhou**
### Check List 

Tests 

 - Unit test
 - Integration test
 - Manual test (add detailed scripts or steps below)
 - No code

Code changes

 - Has exported function/method change
 - Has exported variable/fields change
 - Has interface methods change

Side effects

 - Possible performance regression
 - Increased code complexity
 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch
 - Need to update the documentation
 - Need to be included in the release note

### CODE REVIEW

**Review by kennytm — APPROVED** [review]

**Comment by tangenta** [comment]
@tianzhou Could you sign the CLA so that we can merge your PR?

https://cla-assistant.io/pingcap/parser?pullRequest=1360

**Comment by tianzhou** [comment]
Ping?

**Review by sunxiaoguang — APPROVED** [review]
LGTM

**Comment by tisonkun** [comment]
@xhebox IIUC this repo is merged into pingcap/tidb so that we shouldn't merge it here but create a duplicate on pingcap/tidb?

**Comment by xhebox** [comment]
> @xhebox IIUC this repo is merged into pingcap/tidb so that we shouldn't merge it here but create a duplicate on pingcap/tidb?

Yeah, I will do that later.

**Pull request merged**
