### PR TITLE
ast: Change the implementation of Accept for DefaultExpr

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve? 

This is the part of [pull/19709](https://github.com/pingcap/tidb/pull/19709)

### What is changed and how it works?

This pr will let `DefaultExpr` not generate `ColumnName`

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Comment by rebelice** [comment]
PTAL @AilinKid

**Comment by lysu** [comment]
LGTM

**Review by lysu — APPROVED** [review]

**Pull request merged**
