### PR TITLE
parser: rename topn_to_cop hint to limit_to_cop hint.

### PR DESCRIPTION
**Pull request by tangwz**
### What problem does this PR solve? 
Rename sql hint `topn_to_cop` to `limit_to_cop`.
Issue Number: pingcap/tidb#15549

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change

Side effects

 - None

Related changes

 - None

### CODE REVIEW

**Comment by tangwz** [comment]
@qw4990 PTAL.

Thanks.

**Review by winoros — COMMENTED** [review]
lgtm

**Review by qw4990 — APPROVED** [review]
LGTM

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
