### PR TITLE
parser: add autoid cache option (#765)

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve? 
cherry-pick auto_id_cache #765 to release 3.1

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by AilinKid** [comment]
should the fail be reasonable in build-integration?

**Comment by kennytm** [comment]
@AilinKid dunno, but doesn't look like this PR's fault.

```
FAIL: integration_test.go:2131: testIntegrationSuite.TestBuiltin

integration_test.go:2478:
    result.Check(testkit.Rows("2016-01-01 08:00:00.0000"))
/go/src/github.com/pingcap/tidb/util/testkit/testkit.go:61:
    res.c.Assert(resBuff.String(), check.Equals, needBuff.String(), res.comment)
... obtained string = "[2016-01-01 00:00:00.0000]\n"
... expected string = "[2016-01-01 08:00:00.0000]\n"
... sql:select from_unixtime(14516064000/10), args:[]

----------------------------------------------------------------------
FAIL: builtin_time_test.go:1143: testEvaluatorSuite.TestFromUnixTime

builtin_time_test.go:1190:
    c.Assert(ans.String(), Equals, t.expect, Commentf("%+v", t))
... obtained string = "2016-01-01 00:00:00"
... expected string = "2016-01-01 08:00:00"
... {isDecimal:false integralPart:1451606400 fractionalPart:0 decimal:0 format: expect:2016-01-01 08:00:00}
```

**Comment by AilinKid** [comment]
auto_id_cache support, PTAL @tangenta

**Pull request merged**
