### PR TITLE
parser: support SQL bind capture filter syntax

### PR DESCRIPTION
**Pull request by eurekaka**
### What problem does this PR solve? 

Parser changes for https://github.com/pingcap/tidb/issues/15655

### What is changed and how it works?

Add new syntax for baseline capture filter.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

N/A

Related changes

 - Need to update the documentation

### CODE REVIEW

**Comment by tangenta** [comment]
`NOT IGNORE` sounds counter-intuitive... Can we use `ADD`/`REMOVE` instead?

```
admin capture bindings remove table t1;
admin capture bindings remove table test.t1;
admin capture bindings add table t1;
admin capture bindings add table test.t1;
admin capture bindings remove database db1;
admin capture bindings add database db1;
admin capture bindings show;
```

**Comment by eurekaka** [comment]
> `NOT IGNORE` sounds counter-intuitive... Can we use `ADD`/`REMOVE` instead?
> 
> ```
> admin capture bindings remove table t1;
> admin capture bindings remove table test.t1;
> admin capture bindings add table t1;
> admin capture bindings add table test.t1;
> admin capture bindings remove database db1;
> admin capture bindings add database db1;
> admin capture bindings show;
> ```

The capture filter is blacklist, so we need a negative keyword. The `not ignore` is to remove the item from the blacklist. If we use `add` / `remove`, users may think that only the added items are considered for baseline capture.

**Comment by tangenta** [comment]
Ok. Another question: is it possible to use a system table to represent the blacklist(like `mysql.expr_pushdown_blacklist`)? One of the advantages is that we can use `INSERT`/`DELETE`/`SELECT` to show the list.

**Comment by eurekaka** [comment]
> Ok. Another question: is it possible to use a system table to represent the blacklist(like `mysql.expr_pushdown_blacklist`)? One of the advantages is that we can use `INSERT`/`DELETE`/`SELECT` to show the list, which is easier to learn.

Alright.

**Pull request closed without merging**
