### PR TITLE
types: allows more types to be equal

### PR DESCRIPTION
**Pull request by wjhuang2016**
Signed-off-by: wjhuang2016 <huangwenjun1997@gmail.com>

### What problem does this PR solve? 
varchar and varstring are considered the same.
And their decimal can be ignored.
 
### Check List 

Tests 

 - No code

Code changes

 - Has exported function/method change

Side effects

 

Related changes

### CODE REVIEW

**Review by XuHuaiyu — COMMENTED** [review]
LGTM

**Comment by LittleFall** [comment]
LGTM, seems that need an issue to collect all the changes?

**Comment by wjhuang2016** [comment]
> LGTM, seems that need an issue to collect all the history changes?

I think the comment is enough.

**Review by LittleFall — APPROVED** [review]

**Pull request merged**
