### PR TITLE
add support for INSERT_METHOD

### LINKED ISSUE #415: Fix INSERT_METHOD syntax
Index Issue: pingcap/tidb#11486

These are bad (incompatible) SQL cases:

```sql
ALTER TABLE t INSERT_METHOD = FIRST
ALTER TABLE t INSERT_METHOD FIRST
```

Claim this subtask based on the comments below this issue.

### PR DESCRIPTION
**Pull request by TennyZhuang**
### What problem does this PR solve? 

Resolve #415 

### What is changed and how it works?

Update parser.y to add `INSERT_METHOD` keyword.
Update TableOptions Restore.

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

Related changes

### CODE REVIEW

**Comment by leoppro** [comment]
PTAL
@tangenta

**Comment by TennyZhuang** [comment]
Is it my responsibility to resolve the conflicts?

It seems there will be many conflicts because so many people work on `Parser Compatibility`.

**Comment by tangenta** [comment]
@TennyZhuang Yes, we would appreciate that if you can resolve the conflicts. After getting two `LGTM`, we will merge it as soon as possible.

**Comment by TennyZhuang** [comment]
I have resolve it.

**Pull request merged**
