### PR TITLE
ast,parser: added several expression types to represent keyword arguments

### PR DESCRIPTION
**Pull request by kennytm**
* pingcap/tidb#8891

Added `TimeUnitExpr` to represent time and timestamp units like `SECOND` in `DATE_ADD(time, INTERVAL x SECOND)`.

Added `GetFormatSelectorExpr` to represent the selectors like `DATETIME` in `GET_FORMAT(DATETIME, locale)`.

Added `TrimDirectionExpr` to represent the direction like `BOTH` in `TRIM(BOTH 'x' FROM 'xyz')`.

Changed `FrameBound`'s `Unit` to use `TimeUnitType` directly.

Previously these were all converted into a string or integer `ValueExpr`, which made `Restore()` implementation very ugly.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM
Please address conflicts @kennytm

**Comment by tiancaiamao** [comment]
PTAL @leoppro

**Comment by leoppro** [comment]
i am sorry for blocking this pr

**Comment by kennytm** [comment]
PTAL again @leoppro @tiancaiamao thanks. 

The integration test will be broken until pingcap/tidb#8891 is merged.

**Comment by tiancaiamao** [comment]
PTAL https://github.com/pingcap/tidb/pull/8891 @zz-jason

**Pull request merged**
