### PR TITLE
README: add `Go Report Card` and `CircleCI Status` badge

### PR DESCRIPTION
**Pull request by tiancaiamao**
Just like that

[Go Report Card](https://goreportcard.com/report/github.com/pingcap/parser) [CircleCI Status](https://circleci.com/gh/pingcap/parser) [GoDoc](https://godoc.org/github.com/pingcap/parser)

@lysu

### CODE REVIEW

**Comment by shenli** [comment]
LGTM

**Comment by martianzhang** [comment]
how about add godoc badge

[GoDoc](https://godoc.org/github.com/pingcap/parser)

**Comment by tiancaiamao** [comment]
Good idea @martianzhang

**Comment by tiancaiamao** [comment]
PTAL  @jackysp

**Pull request merged**
