### PR TITLE
Update BACKUP/RESTORE syntax to match the RFC; Added IMPORT statement

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Update the parser syntax to match pingcap/tidb#15274.

### What is changed and how it works?

1. Removed the S3/GCS-specific options
2. Removed the "INCREMENTAL UNTIL" syntax, replaced by the "LAST_BACKUP" option
3. The "SHOW BACKUP" statement is renamed to "SHOW BACKUPS".
4. Added "IMPORT" statement (fix pingcap/tidb-lightning#293)

(Recommended: [ignore whitespace](https://github.blog/2018-05-01-ignore-white-space-in-code-review/) when reviewing).

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported variable/fields change

Side effects

Related changes

### CODE REVIEW

**Comment by kennytm** [comment]
PTAL @zz-jason

**Comment by kennytm** [comment]
PTAL @tangenta

**Comment by kennytm** [comment]
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
