### PR TITLE
parser: add a compatibility tester and reporter with mysql and tidb parser

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
This PR adds a compatibility test tool, which generates SQL case from MySQL yacc file (by sequentially or randomly) and compare the behavior between MySQL and TiDB.

### What is changed and how it works?
1. this tester generates SQL case from MySQL yacc file by sequentially or randomly.
2. run SQL case in TiDB parser and MySQL.
3. compare the behavior between MySQL and TiDB.
4. output the incompatible case into a CSV report file.

### Check List 

Tests 

- [x] Unit test
- [ ] Integration test
- [x] Manual test (add detailed scripts or steps below)
we already use this tool to generate bad case.
- [ ] No code

Code changes

- [x]  Has exported function/method change
export two SQL generator used by this tester.
- [ ] Has exported variable/fields change
- [ ] Has interface methods change

Side effects

 - Possible performance regression
None
 - Increased code complexity
None
 - Breaking backward compatibility
None

Related changes

 - Need to update the documentation
already add a readme file.

### CODE REVIEW

**Comment by leoppro** [comment]
@GregoryIan @winkyao PTAL
@tangenta

**Comment by leoppro** [comment]
Note that I use a new interface`io.StringWriter` in go 1.12, so I update the go version in circleci

**Comment by kennytm** [comment]
How `mysql80_bnf.txt` is created? Is it GPL'ed?

**Comment by leoppro** [comment]
> How `mysql80_bnf.txt` is created? Is it GPL'ed?

https://github.com/pingcap/parser/pull/387/files#diff-efa533c14947f2e54885ea7da54cce61R35

it's a part of the mysql source code, I have no idea that whether it's GPL'ed, it a legal issues.

**Comment by zz-jason** [comment]
@leoppro Is this PR ready to be reviewed?

**Comment by leoppro** [comment]
Oh, I even forgot it. We need remove mysql bnf file and then it will ready to review

**Comment by leoppro** [comment]
this pr has been ready to reviewed @zz-jason

**Comment by tiancaiamao** [comment]
This is pretty old, I'll mark a needs-rebase tag

**Comment by tisonkun** [comment]
Closed as stale a while.

Thanks for submitting this PR @leoppro ! You can make another PR based on nightly master later.

**Pull request closed without merging**
