### PR TITLE
Rename is truth to IsTruthWithoutNull

### PR DESCRIPTION
**Pull request by wshwsh12**
### What problem does this PR solve? 
Related pr: https://github.com/pingcap/tidb/pull/19621

### What is changed and how it works?

Rename ast.IsTruth to ast.IsTruthWithoutNull.

### Check List 

Tests 

 - Unit test
 - Integration test

Code changes

 - Has exported variable/fields change

Side effects

 - Breaking backward compatibility

Related changes

 - Need to cherry-pick to the release branch 3.0,4.0

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM.
And should we also do the same thing on `isfalse`(separating it to `IsFalseWithNull` and `IsFlaseWIthoutNull`)?

**Comment by wshwsh12** [comment]
> LGTM.
> And should we also do the same thing on `isfalse`(separating it to `IsFalseWithNull` and `IsFlaseWIthoutNull`)?

Now only IsTruth function maybe set KeepNull true.

**Review by SunRunAway — COMMENTED** [review]
LGTM

**Comment by qw4990** [comment]
@AilinKid Please help us merge this PR.

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
