### PR TITLE
ci: remove github action on pull request

### PR DESCRIPTION
**Pull request by purelind**
### What problem does this PR solve? 
remove github action on pull request, jenkins verify ci will run on every pr

### Check List 

Tests 

 - No code

Related changes

 - Need to cherry-pick to the release-4.0 / release-5.0 / release-5.1 / release-5.2

### CODE REVIEW

**Comment by purelind** [comment]
cc @zhouqiang-cl

**Comment by tisonkun** [comment]
I think you can just remove the github actions file.

**Review by tisonkun — CHANGES_REQUESTED** [review]
I think you can just remove the github actions file.

**Comment by purelind** [comment]
> I think you can just remove the github actions file.

jenkins-parser/verify only runs on pull request

**Comment by tisonkun** [comment]
> > I think you can just remove the github actions file.
> 
> jenkins-parser/verify only runs on pull request

Hmmm...Then things go really weird that we are in an intermediate stage. Any plan to run this set of test on commits without GitHub Actions? Or we just make sure PR passed and thus commits?

**Comment by purelind** [comment]
> > > I think you can just remove the github actions file.
> > 
> > 
> > jenkins-parser/verify only runs on pull request
> 
> Hmmm...Then things go really weird that we are in an intermediate stage. Any plan to run this set of test on commits without GitHub Actions? Or we just make sure PR passed and thus commits?

Done! Now github action on branch master has been removed

**Review by tisonkun — CHANGES_REQUESTED** [review]
Repeat: I think you can just remove the github actions file.

**Review by tisonkun — APPROVED** [review]

**Review by tangenta — APPROVED** [review]

**Comment by tisonkun** [comment]
@purelind if you turn on verify ci on all branches, could you please cherry pick this PR to all those branches?

**Pull request merged**
