### PR TITLE
ast: Change the implementation of Accept for DefaultExpr

### PR DESCRIPTION
**Pull request by rebelice**
### What problem does this PR solve? 

This is the part of [pull/19709](https://github.com/pingcap/tidb/pull/19709)

### What is changed and how it works?

This pr will let `DefaultExpr` not generate `ColumnName`

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

### CODE REVIEW

**Review by qw4990 — COMMENTED** [review]
LGTM

**Review by eurekaka — APPROVED** [review]
LGTM

**Comment by AilinKid** [comment]
better fix the corresponding panic in TiDB with another or and merge this two together
```
PANIC: expression_rewriter_test.go:65: testExpressionRewriterSuite.TestDefaultFunction

... Panic: runtime error: index out of range [-1] (PC=0x1246961)

/usr/local/go/src/runtime/panic.go:679
  in gopanic
/usr/local/go/src/runtime/panic.go:75
  in goPanicIndex
expression_rewriter.go:1624
  in expressionRewriter.evalDefaultExpr
```

**Comment by rebelice** [comment]
> better fix the corresponding panic in TiDB with another pr and merge this two together
> 
> ```
> PANIC: expression_rewriter_test.go:65: testExpressionRewriterSuite.TestDefaultFunction
> 
> ... Panic: runtime error: index out of range [-1] (PC=0x1246961)
> 
> /usr/local/go/src/runtime/panic.go:679
>   in gopanic
> /usr/local/go/src/runtime/panic.go:75
>   in goPanicIndex
> expression_rewriter.go:1624
>   in expressionRewriter.evalDefaultExpr
> ```
This is the corresponding [pr](https://github.com/pingcap/tidb/pull/19709) in TiDB. But how to merge them together?

**Review by AilinKid — APPROVED** [review]
LGTM

**Pull request merged**
