### PR TITLE
parser: add cast check

### PR DESCRIPTION
**Pull request by pengdaqian2020**
### What problem does this PR solve? 

[#21064](https://github.com/pingcap/tidb/issues/21063)

### What is changed and how it works?

add decimal scale and precision check

### Check List

Tests

 - Unit test
 - Integration test
 
Code changes

 - Has exported function/method change
No
 - Has exported variable/fields change
No
 - Has interface methods change
No

Side effects

 - Possible performance regression
No
 - Increased code complexity
No
 - Breaking backward compatibility
No

Related changes

 - Need to cherry-pick to the release branch
yes
 - Need to update the documentation
No
 - Need to be included in the release note
No

### CODE REVIEW

**Comment by pengdaqian2020** [comment]
@blacktear23 
PLAT

**Comment by kennytm** [comment]
Hi, thanks for the contribution.

Unfortunately I need to push back on this direction of adding semantic checks directly into `parser.y`. As we know `pingcap/parser` is not _just_ used for TiDB. Officially it is also used in DM for parsing MySQL and MariaDB DDLs, and this package is also [used by third-party](https://pkg.go.dev/github.com/pingcap/parser?tab=importedby) for generating AST from SQL. 

Therefore, semantic checks like this PR _only_ benefits TiDB, but limits legit third-party usage (like performing [AST transformation](https://github.com/XiaoMi/soar) which shouldn't be tripped by `DECIMAL(1000,20)`, or maybe building a MyBigNumDB which legit supports `DECIMAL(1000,20)`).

IMO the proper way is to check the AST after parsing, like:

```go
statements, _warns, _err := p.Parse("sql", "", "")
verifier := NewTiDBVerifier() // bundle all TiDB-specific semantic checks into this Visitor
for _, stmt := range statements {
    if _, ok := stmt.Accept(verifier); !ok {
        return verifier.Err()
    }
}
```

The idea of placing the semantic checks directly in `parser.y` to generate errors and warnings has been tried several times and also moved back to TiDB later (#965, #888, #795, #920, #914). Let's not repeat this again.

cc #1097 @blacktear23

**Comment by blacktear23** [comment]
@kennytm Agreed

**Comment by blacktear23** [comment]
@pengdaqian2020 sorry for my misleading.

**Comment by pengdaqian2020** [comment]
> @pengdaqian2020 sorry for my misleading.

:joy: so it seems I should check it in `preprocessor` ?

**Comment by blacktear23** [comment]
> > @pengdaqian2020 sorry for my misleading.
> 
> 😂 so it seems I should check it in `preprocessor` ?

Yes. 😂

**Pull request closed without merging**
