### PR TITLE
Model: add the new field to the Job Struct.

### PR DESCRIPTION
**Pull request by ou-bing**
### What problem does this PR solve? 
Support to delete multiple indexes in one statement.

### What is changed and how it works?
Add the new field to the Job Struct, I want to save some warnings when performing the change multi-schema operation.

### CODE REVIEW

**Comment by ou-bing** [comment]
@zimulala Here is the new PR for multi-schema change.

**Review by tangenta — APPROVED** [review]

**Comment by kennytm** [comment]
@tisonkun should we cherry-pick this to release-{4.0, 5.0, 5.1}?

**Comment by tisonkun** [comment]
@kennytm I'm not the person to make decision. May @tiancaiamao and you as the leader of sql-infra conclude it.

For suggestion, I don't see even the background as an issue or other link for this PR so that it is hard to say whether pick or not.

**Comment by kennytm** [comment]
Sorry, wrong issue link, meant to comment on #1247 😅  @tisonkun

**Review by zimulala — APPROVED** [review]
LGTM

**Pull request merged**
