### PR TITLE
parser: update the broken link for Contribution Guide in README.md

### PR DESCRIPTION
**Pull request by nayuta-yanagisawa**
### What problem does this PR solve? 

CONTRIBUTING.md was moved and the link to it in README.md is broken.

Related PR: https://github.com/pingcap/tidb/pull/20964

### What is changed and how it works?

Just replace the broken link in README.

### Check List 

Tests 

 - No code

### CODE REVIEW

**Comment by nayuta-yanagisawa** [comment]
Some integration tests fail. However, this seems not due to my change bucause there is no code diff.

**Review by kennytm — APPROVED** [review]
LGTM

**Review by tangenta — COMMENTED** [review]
LGTM

**Pull request merged**
