### PR TITLE
Fix AST.Restore() restore char(1) to char(1,0)

### PR DESCRIPTION
**Pull request by leoppro**
### What problem does this PR solve? 
See issue: pingcap/tidb#11470

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by leoppro** [comment]
@kennytm @AilinKid PTAL

**Comment by kennytm** [comment]
😕 Why `ft.Decimal == 0` in the first place?

**Comment by leoppro** [comment]
@kennytm PTAL again

**Comment by leoppro** [comment]
blocked by https://github.com/pingcap/tidb/pull/11553

**Pull request merged**
