### PR TITLE
parser: Support FLUSH LOGS, FLUSH HOSTS sql commands (#140)

### PR DESCRIPTION
**Pull request by CorefLava**
### What problem does this PR solve? 

Feat issue [parser/#140](https://github.com/pingcap/parser/issues/140) based on https://dev.mysql.com/doc/refman/5.7/en/flush.html

### What is changed and how it works?

Parser will return FlushStmt with type = FlushHosts / FlushLogs instead of error

### Check List 

Tests 

 - Unit test

Code changes

 - Has exported function/method change
 - Has exported variable/fields change

Side effects

 - Increased code complexity

Related changes

- Tidb will return ok instead of error if parser accepts the grammar, which has been premitted in issue [tidb/#2544](https://github.com/pingcap/tidb/issues/2544)

### CODE REVIEW

**Comment by morgo** [comment]
@jackysp PTAL

**Comment by jackysp** [comment]
Thanks for your contribution! @CorefLava 
PTAL @tiancaiamao

**Comment by tiancaiamao** [comment]
LGTM @jackysp

**Comment by jackysp** [comment]
Please resolve the conflicts. @CorefLava

**Comment by tiancaiamao** [comment]
Please sign CLA @morgo @CorefLava

**Comment by kennytm** [comment]
Hello @CorefLava, would you mind signing the CLA above (https://github.com/pingcap/parser/pull/238#issuecomment-496850527) and fix the merge conflict? We can't merge this PR without the CLA check passing. Thanks 🙂.

**Comment by zz-jason** [comment]
@CorefLava Any update? Please resolve the conflicts.

**Pull request closed without merging**
