### PR TITLE
parser: change attributes to an unreserved keyword

### PR DESCRIPTION
**Pull request by rleungx**
### What problem does this PR solve? 
Use `ATTRIBUTES` as a keyword that may introduce some problems like https://github.com/pingcap/tidb/issues/26778.

### What is changed and how it works?

This PR is going to change it to an unreserved keyword.

### Check List 

Tests 

 - Unit test

Related changes
 - Need to update the documentation

### CODE REVIEW

**Review by djshow832 — APPROVED** [review]

**Review by nolouch — APPROVED** [review]

**Review by xhebox — APPROVED** [review]

**Comment by xhebox** [comment]
@rleungx  Also need an update of parser on TiDB.

**Review by tangenta — APPROVED** [review]

**Comment by tangenta** [comment]
Reopen to activate license/cla check.

**Comment by rleungx** [comment]
The cla has something wrong at the moment, I think.

**Pull request merged**
