### PR TITLE
ast: fix the TiDB issue #8153

### PR DESCRIPTION
**Pull request by dbjoa**
Required in the TiDB PR [#8206](https://github.com/pingcap/tidb/pull/8206)

### CODE REVIEW

**Comment by shenli** [comment]
@dbjoa Thanks!
Please rebase the master and generate the `parser.go` again. We have fixed an issue that the generated parser.go is not stable. See: https://github.com/pingcap/parser/pull/9

**Comment by dbjoa** [comment]
@shenli Thank you for the guide. I've updated the PR.

**Comment by tiancaiamao** [comment]
PTAL @zz-jason @eurekaka

**Comment by shenli** [comment]
LGTM

**Comment by zz-jason** [comment]
Hi @dbjoa, could you help us cherry pick this commit to the release-2.1 branch? I tried to cherry-pick but failed. Seems you need to sign the CLA?

**Comment by dbjoa** [comment]
@zz-jason 
I've just signed the CLA.

**Pull request merged**
