### PR TITLE
improve:GetCharsetDesc

### PR DESCRIPTION
**Pull request by hhxcc**
### What problem does this PR solve? 
pingcap/tidb#9635

### What is changed and how it works?
GetCharsetDesc  now get desc from inited variable descs.

### Check List 

Tests 

 - Unit test

Code changes
 - Has exported function/method change

Related changes

 - Need to update go.mod in tidb

### CODE REVIEW

**Comment by hhxcc** [comment]
Benchmark GetCharsetDesc.

Before:
```
GO111MODULE=on go test -run GetCharsetDesc   -bench Benchmark  github.com/pingcap/parser/charset
goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetCharsetDesc-8       20000000                54.5 ns/op
PASS
ok      github.com/pingcap/parser/charset       1.160s
```


After:
```
GO111MODULE=on go test -run GetCharsetDesc   -bench Benchmark  github.c
om/pingcap/parser/charset
goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetCharsetDesc-8       100000000               13.4 ns/op
PASS
ok      github.com/pingcap/parser/charset       1.361s
```

**Comment by hhxcc** [comment]
@ngaut PTAL

**Comment by ngaut** [comment]
LGTM

**Comment by ngaut** [comment]
Thank you @hhxcc  
Please sign the CLA.

**Comment by hhxcc** [comment]
@ngaut  ok, done.

**Comment by lysu** [comment]
@kennytm please sign the CLA too o.o~

**Pull request merged**
