### PR TITLE
*: add `IF EXISTS` and `IF NOT EXISTS` supported for MariaDB

### PR DESCRIPTION
**Pull request by csuzhangxc**
### What problem does this PR solve? 

for MaraiDB 10.0.2+, `ALTER TABLE` support `IF EXISTS` and `IF NOT EXISTS` clauses for some statements, and `CREATE INDEX` also support `IF NOT EXISTS`.

see <https://mariadb.com/kb/en/library/alter-table/> and <https://mariadb.com/kb/en/library/create-index/>

### What is changed and how it works?

1. add `IF EXISTS` for
	1. `DROP COLUMN`
	2. `CHANGE COLUMN`
	3. `MODIFY COLUMN`
	4. `DROP INDEX`
	5. `DROP FOREIGN KEY`
	6. `DROP PARTITION`
2. add `IF NOT EXISTS` for
	1. `ADD COLUMN`
	2. `ADD INDEX`
	3. `ADD FOREIGN KEY`
	4. `CREATE INDEX`
	5. `ADD PARTITION`

### Check List 

Tests 

 - Unit test

Corresponding TiDB PR: https://github.com/pingcap/tidb/pull/10723

### CODE REVIEW

**Comment by kennytm** [comment]
@csuzhangxc  Is there a corresponding TiDB PR? Otherwise supporting these in the parser level would be misleading.

**Comment by csuzhangxc** [comment]
> @csuzhangxc Is there a corresponding TiDB PR? Otherwise supporting these in the parser level would be misleading.

@kennytm not yet, but I'll open one.

**Comment by tiancaiamao** [comment]
LGTM @winkyao

**Comment by csuzhangxc** [comment]
@kennytm @tiancaiamao PTAL again

I also add:
- `IF NOT EXISTS` for `ADD PARTITION`
- `IF EXISTS` for `DROP PARTITION`

**Comment by winkyao** [comment]
@csuzhangxc Just parse it and ignore it?

**Comment by tiancaiamao** [comment]
Would you like to update `parser.go`, please? @csuzhangxc

**Comment by csuzhangxc** [comment]
> Would you like to update `parser.go`, please? @csuzhangxc

@tiancaiamao updated and resolved the conflicts.

**Pull request merged**
