### PR TITLE
remove GrantPriv from AllGlobalPrivs/AllDBPrivs/AllTablePrivs

### PR DESCRIPTION
**Pull request by tsthght**
### What problem does this PR solve? 
for https://github.com/pingcap/tidb/pull/12330

### What is changed and how it works?
remove GrantPriv from AllGlobalPrivs, AllDBPrivs, AllTablePrivs

### CODE REVIEW

**Comment by tiancaiamao** [comment]
LGTM

**Comment by AilinKid** [comment]
should we modify `c.Assert(len(mysql.Priv2UserCol), Equals, len(mysql.AllGlobalPrivs))` in `privilege_test.go` to pass the  build-integration CI?

**Comment by kennytm** [comment]
@AilinKid Yes you're supposed to follow up on the TiDB repository to update the test cases given the latest parser.

**Comment by ekalinin** [comment]
Fixed tests here:
- https://github.com/pingcap/tidb/pull/12804/commits/8f2f77c9357f793f4aeae12dcaabe38419f7cb27

**Pull request merged**
