### PR TITLE
improve: GetAllCharsets and GetCharsetInfoByID

### PR DESCRIPTION
**Pull request by hawkingrei**
### What problem does this PR solve? 
https://github.com/pingcap/tidb/issues/9635
some of the functions may just return constants. There is no need to do compute every time if we save a map/slice and initialize them. Such as: GetAllCharsets and GetCharsetInfoByID 

### What is changed and how it works?

1. GetAllCharsets is inited at the init function, and GetAllCharsets can return the inited array directly.
2. GetCharsetInfoByID use a map to fetch Collation effectively, init the map in the init function too.

### Check List 
 - Unit test

Code changes
 - improve GetAllCharsets and GetCharsetInfoByID
 
Related changes
 - Need to update go.mod in tidb

### CODE REVIEW

**Comment by shenli** [comment]
@hawkingrei Thanks!
Is there any benchmark result to show the improvement?

**Comment by hawkingrei** [comment]
BenchmarkGetAllCharsets

Before improve:

```
go test -bench Benchmark -run GetAllCharsets ./... -count 5

goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetAllCharsets-4   	 3000000	       405 ns/op
BenchmarkGetAllCharsets-4   	 3000000	       405 ns/op
BenchmarkGetAllCharsets-4   	 3000000	       397 ns/op
BenchmarkGetAllCharsets-4   	 3000000	       447 ns/op
BenchmarkGetAllCharsets-4   	 3000000	       443 ns/op
PASS
ok  	github.com/pingcap/parser/charset	8.616s
PASS
```

After improve
```
go test -bench Benchmark -run GetAllCharsets ./... -count 5

goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetAllCharsets-4   	2000000000	         0.38 ns/op
BenchmarkGetAllCharsets-4   	2000000000	         0.37 ns/op
BenchmarkGetAllCharsets-4   	2000000000	         0.37 ns/op
BenchmarkGetAllCharsets-4   	2000000000	         0.36 ns/op
BenchmarkGetAllCharsets-4   	2000000000	         0.36 ns/op
PASS
```

Here is benchmark code.

```
func BenchmarkGetAllCharsets(b *testing.B) {
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		GetAllCharsets()
	}
}
```

**Comment by hawkingrei** [comment]
Benchmark GetAllCharsets

Before improve:

```
go test -bench Benchmark -run GetGetCharsetInfoByID ./... -count 2

goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetCharsetInfoByID-4   	30000000	        64.4 ns/op
BenchmarkGetCharsetInfoByID-4   	30000000	        72.4 ns/op
PASS
ok  	github.com/pingcap/parser/charset	4.208s
```

After improve

```
go test -bench Benchmark -run GetGetCharsetInfoByID ./... -count 2

goos: darwin
goarch: amd64
pkg: github.com/pingcap/parser/charset
BenchmarkGetCharsetInfoByID-4   	100000000	        20.6 ns/op
BenchmarkGetCharsetInfoByID-4   	100000000	        18.5 ns/op
PASS
```

Here is benchmark code.

```
func BenchmarkGetCharsetInfoByID(b *testing.B) {
	index := rand.Intn(248)
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		GetCharsetInfoByID(index)
	}
}
```

**Comment by hawkingrei** [comment]
@shenli  it looks good

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
