### PR TITLE
Unreserved 8 keywords

### LINKED ISSUE #846: SQL syntax parsing exception when the field name in the SQL statement is `error`
## Bug Report
SQL syntax parsing exception when the field name in the SQL statement is `error`,

1. What did you do?
If possible, provide a recipe for reproducing the error.
```
func TestExample(t *testing.T) {
	p := parser.New()
	stmtNodes, _, err := p.Parse("select message_id,error,update_time from test", "", "")
	fmt.Println(stmtNodes[0], err)
}
```

2. What did you expect to see?
Get sql syntax tree

3. What did you see instead?
Syntax parsing exception
```
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
goroutine 36 [running]:
```
4. What version of TiDB SQL Parser are you using?
v0.0.0-20200218113622-517beb2e39c2

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix #846.

### What is changed and how it works?

Unreserved the following 8 keywords:

* chain
* error
* general
* nvarchar
* pack_keys
* parser
* shard_row_id_bits
* pre_split_regions

And added a manually executed test case to ensure the list of reserved keywords mostly match that of MySQL. The only discrepancy currently are:

* **current_role** — reserved in TiDB, not reserved in MySQL (introduced by #228, caused significant reduce/reduce conflict when unreserved, cc @imtbkcat)
* **function** — reserved since MySQL 8.0.1, not reserved in TiDB
* **separator** — reserved in MySQL (why?), not reserved in TiDB

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to cherry-pick to the release branch
    * Affects all TiDB versions.

### Release note 

* `CHAIN`, `ERROR`, `GENERAL`, `NVARCHAR`, `PACK_KEYS`, `PARSER`, `SHARD_ROW_ID_BITS` and `PRE_SPLIT_REGIONS` are no longer treated as reserved words.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
`shard_row_id_bits` and `pre_split_regions`, should them be unreserved-keyword or non-keyword?

**Comment by kennytm** [comment]
hmm what's the difference between UnreservedKeyword, NotKeyword and TiDBKeyword?

**Comment by tiancaiamao** [comment]
> hmm what's the difference between UnreservedKeyword, NotKeyword and TiDBKeyword?

I'm not sure there is any difference between NonKeyword and UnreservedKeyword.
NonKeyword is solely a identifier, whereas UnreservedKeyword can alse be used just like an identifier (no need to warp with `), so I can't tell apart them.

https://dev.mysql.com/doc/refman/5.7/en/keywords.html

If you are not sure as well, I think we can merge this change. Anyway, nobody knows or cares about it. @kennytm

**Comment by tiancaiamao** [comment]
LGTM

**Comment by kennytm** [comment]
okay.

**Comment by lysu** [comment]
hi @kennytm  could please help cherry-pick this to 3.0 and 3.1, some customers meet this problem too in 3.0, thanks~

**Comment by kennytm** [comment]
@lysu #928, #929.

**Pull request merged**
