### PR TITLE
issues 280: Support ON UPDATE ddl statements

### PR DESCRIPTION
**Pull request by gleonid**
### What problem does this PR solve? 
"CREATE TABLE child ( id INT, parent_id INT, INDEX par_ind (parent_id), FOREIGN KEY (parent_id) REFERENCES parent(id) ON UPDATE CASCADE)" fails to parse even though grammar looks like it should b able to

### What is changed and how it works?
1. Added a unit test for above (see changes to ast/ddl_test.go)
2. refactored slightly grammar definition to explicitly enumerate all 4 possible combinations:
` ReferDef: "REFERENCES" TableName '(' IndexColNameList ')' OnDeleteOpt OnUpdateOpt` is replaced with
```
 ReferDef:
       "REFERENCES" TableName '(' IndexColNameList ')' OnDeleteUpdateOpt
...
OnDeleteUpdateOpt:
    OnDelete OnUpdate
    {
        $$ = OnDeleteUpdateDef{ $1.(*ast.OnDeleteOpt), $2.(*ast.OnUpdateOpt) }
       }
|   OnUpdate
    {
        $$ = OnDeleteUpdateDef{ &ast.OnDeleteOpt{}, $1.(*ast.OnUpdateOpt) }
    } %prec lowerThanOn
|   OnDelete
    {
        $$ = OnDeleteUpdateDef{ $1.(*ast.OnDeleteOpt), &ast.OnUpdateOpt{} }
    } %prec lowerThanOn
|   {
               $$ = OnDeleteUpdateDef{ &ast.OnDeleteOpt{}, &ast.OnUpdateOpt{} }
       } %prec lowerThanOn
```

### Check List 

Tests 

 - Unit test
  **added**

Code changes

 - Has exported function/method change
**no**
 - Has exported variable/fields change
**no**
 - Has interface methods change
**no**

Side effects
 - Possible performance regression
      performance test was not performed
 - Breaking backward compatibility
     existing tests pass

### CODE REVIEW

**Comment by gleonid** [comment]
I have signed "You have signed the CLA for pingcap/parser" on 13:03 EST, yet it still shows as not signed in checklist above

**Comment by kennytm** [comment]
@gleonid Thanks for the contribution.

The CLA Bot relies on the your email address registered on GitHub as a proof of signature. If the address used to author 5ead50a (`leonid.gershanovich@xandr.com`) is not associated to your GitHub account, the CLA check won't pass. You may amend the commit using the GitHub email address, or add this `xandr.com` address to GitHub following https://help.github.com/en/articles/adding-an-email-address-to-your-github-account.

**Comment by tiancaiamao** [comment]
LGTM
PTAL @winkyao

**Comment by gleonid** [comment]
@winkyao
Please decide faith of this PR

I can resolve conflict on parser.go (generated file), but most likely it will become a conflict again as soon as any change to grammar is made (another PR merged).

I have parser.go as a separate commit, specifically for purpose to simplify rebasing.
I am happy to do at any point, or you can do it as easily.

Please let me know how you'd like to proceed

**Comment by winkyao** [comment]
These changes are approved, thanks for your contribution

**Comment by gleonid** [comment]
> 
> 
> @gleonid Could you resolve the conflicts?
@winkyao 
conflict has been resolved

**Comment by winkyao** [comment]
The CI is failed with error:

```
----------------------------------------------------------------------
FAIL: write_test.go:1747: testSuite4.TestQualifiedDelete

write_test.go:1768:
    c.Assert(err, NotNil)
... value = nil
```

@crazycs520 will help to fix ci.

**Comment by kennytm** [comment]
@winkyao The integration test error will be fixed by pingcap/tidb#11184.

**Comment by gleonid** [comment]
conflict is resolved but now approval is required again

**Pull request merged**
