### PR TITLE
parser: support DELETE FROM ... AS ... syntax

### PR DESCRIPTION
**Pull request by kennytm**
### What problem does this PR solve? 

Fix issue pingcap/tidb#11173. The `DELETE FROM ... AS ...` syntax was introduced in [MySQL 8.0.16](https://dev.mysql.com/doc/refman/8.0/en/delete.html).

### What is changed and how it works?

Recognize the new syntax in the parser.

### Check List 

Tests 

 - Unit test

Code changes

Side effects

Related changes

 - Need to update the documentation
    * May need to update https://pingcap.com/docs/v3.0/reference/sql/statements/delete/ if it is not auto-generated.

### CODE REVIEW

**Comment by kennytm** [comment]
(Integration test requires pingcap/tidb#11184 to pass)

**Comment by kennytm** [comment]
PTAL @tiancaiamao @shenli

**Comment by imtbkcat** [comment]
Hi kennytm, i try to run this SQL in MySQL 8.0, but failed.

```
mysql> DELETE FROM x t WHERE t.a = 4;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 't WHERE t.a = 4' at line 1
```

**Comment by kennytm** [comment]
@imtbkcat 

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-16.html

>  For consistency with the SQL standard and other RDBMS, table aliases are now supported in single-table as well as multi-table `DELETE` statements. (Bug #27455809)

**Comment by bb7133** [comment]
hi @kennytm , please update TiDB test case:

(write_test.go:1747: `testSuite4.TestQualifiedDelete`)
```
1767     _, err := tk.Exec("delete from t1 as a where a.c1 = 1")
1768     c.Assert(err, NotNil)
```

**Pull request merged**
