### PR TITLE
parser: introduce a new privilege for the `set config` statement

### LINKED ISSUE #826: Introduce a new privilege for the `set config` statement
## Feature Request

**Describe the feature you'd like:**

After https://github.com/pingcap/parser/issues/768, we can use `set config` on TiDB to update configs of TiKV/PD.
Now the privilege of this statement is `PrivSuper`, which is not appropriate.
We should introduce a new privilege for it.

**Describe alternatives you've considered:**

No

### PR DESCRIPTION
**Pull request by qw4990**
### What problem does this PR solve? 
Close #826.
After https://github.com/pingcap/parser/issues/768, we can use `set config` on TiDB to update configs of TiKV/PD.
Now the privilege of this statement is `PrivSuper`, which is not appropriate.
We should introduce a new privilege for it.

### What is changed and how it works?
Introduce a new privilege `CONFIG_PRIV`.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Comment by tiancaiamao** [comment]
The build-integration test seems to be failed, is there a corresponding PR in TiDB?

**Comment by qw4990** [comment]
> The build-integration test seems to be failed, is there a corresponding PR in TiDB?

Yes, it's https://github.com/pingcap/tidb/pull/16847.

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
