### PR TITLE
parser : support admin repair table syntax

### PR DESCRIPTION
**Pull request by AilinKid**
### What problem does this PR solve? 
For ISSUE to fix  tableInfo (Meta) in KV store.  
Bad tableInfo will be loaded error leading TiDB crash when it restart.
So we support a new syntax to repair bad tableInfo in meta (using new tableInfo build from create table statement to override the bad tableInfo, that means user should keep new tableInfo correct)

Backgound : In some corner cases or encountering serious bugs, DDL operations update table structure error occurred, causing TiDB panic and failing to restart the service.

```
ADMIN REPAIR TABLE  table_name CREATE TABLE STATEMENT
```

Related TiDB PR [#12046](https://github.com/pingcap/tidb/pull/12046)
Related Design Doc : [fix broken table](https://docs.google.com/document/d/1u5sPhh3FL8VGvCDnp0-iEzA9BGCCLHtgRhtjxj623Dk/edit)

### What is changed and how it works?
In adminstmt parser.yy : add a new syntax
ADMIN REPAIR TABLE  table_name CREATE TABLE STATEMENT

### Check List 

Tests 

 - Unit test
 - Integration test

### CODE REVIEW

**Comment by kennytm** [comment]
The syntax looks weird. What happens with `ADMIN REPAIR TABLE x CREATE TABLE y ...` ?

**Comment by AilinKid** [comment]
> The syntax looks weird. What happens with `ADMIN REPAIR TABLE x CREATE TABLE y ...` ?

just rename the table.

**Comment by AilinKid** [comment]
> The syntax looks weird. What happens with `ADMIN REPAIR TABLE x CREATE TABLE y ...` ?

just rename the table, cause override will use the old table id, index id, so it's ok.

**Comment by tiancaiamao** [comment]
LGTM
I hope we never use it although.

**Comment by AilinKid** [comment]
@kennytm @tangenta PTAL

**Pull request merged**
