### PR TITLE
charset: add 'char set' syntax support

### PR DESCRIPTION
**Pull request by tangenta**
### What problem does this PR solve? 
```sql
alter database char set = utf8mb4;
```
In MySQL:  
```sql
Query OK (0.001 sec)
```

In TiDB:  
```sql
Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your TiDB version for the right syntax to use line 1 column 19 near "char set = utf8mb4"
```

### What is changed and how it works?

Add `"char" "set"` body to  `CharsetKw` in parser.y

### Check List 

Tests 

 - Integration test

### CODE REVIEW

**Comment by tangenta** [comment]
@kennytm PTAL

**Comment by leoppro** [comment]
@tiancaiamao PTAL

**Comment by tangenta** [comment]
```
----------------------------------------------------------------------
FAIL: write_test.go:1747: testSuite4.TestQualifiedDelete

write_test.go:1768:
    c.Assert(err, NotNil)
... value = nil
```

**Comment by bb7133** [comment]
> ```
> ----------------------------------------------------------------------
> FAIL: write_test.go:1747: testSuite4.TestQualifiedDelete
> 
> write_test.go:1768:
>     c.Assert(err, NotNil)
> ... value = nil
> ```

This is caused by another PR, I will fix it soon.

**Pull request merged**
