### PR TITLE
digester: consider paramMarker as literal when normalizing SQL

### PR DESCRIPTION
**Pull request by time-and-fate**
### What problem does this PR solve? 

https://github.com/pingcap/tidb/issues/19836

Currently, `normalize()` doesn't handle `paramMarker`('?'), this makes some bindings can't work as expected like the issue above.

Prepared statement `select * from t limit ?, ?` is normalized to `select * from t limit ?, ?`. However, a binding for `select * from t limit 1, 2` is normalized to and can only be matched by `select * from t limit ...`.

### What is changed and how it works?

When normalizing SQL, consider `paramMarker` as literal, this will make `paramMarker` be normalized to `genericSymbol`. This makes sense also because both `paramMarker` and `genericSymbol` correspond to '?'.

After this change, `select * from t limit ?, ?` will be normalized to `select * from t limit ...` instead of `select * from t limit ?, ?`.

### Check List 

Tests 

 - Unit test

### CODE REVIEW

**Review by eurekaka — COMMENTED** [review]
LGTM

**Comment by time-and-fate** [comment]
@SunRunAway PTAL~

**Comment by eurekaka** [comment]
@SunRunAway PTAL

**Comment by kennytm** [comment]
LGTM

**Review by eurekaka — APPROVED** [review]

**Pull request merged**
