### PR TITLE
ast: Fix FrameBound.Accept

### PR DESCRIPTION
**Pull request by spongedu**
`FrameBound.Unit` should be processed instead of `FrameBound.Expr` here.

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @zz-jason

**Comment by zz-jason** [comment]
@spongedu Could you add some UT for this bug?

**Comment by kennytm** [comment]
UT = Unit Tests?

**Comment by spongedu** [comment]
@zz-jason  Add some unittests for this.  PTAL

**Pull request merged**
