### PR TITLE
fix now frac in column option

### PR DESCRIPTION
**Pull request by Ryan-Git**
### What problem does this PR solve? 
https://github.com/pingcap/parser/issues/186 is not completely fixed by #211 , this PR parses fraction of CURRENT_TIMESTAMP in ON UPDATE clause.

### What is changed and how it works?
ref parsed NowSymOptionFraction in ColumnOption rather than manually construct it.

### Check List 

Tests 

adjusted related parser_test.go

### CODE REVIEW

**Comment by tiancaiamao** [comment]
PTAL @winkyao @crazycs520

**Comment by Ryan-Git** [comment]
any update?

**Comment by tiancaiamao** [comment]
PTAL @winkyao @crazycs520

**Comment by tiancaiamao** [comment]
LGTM

**Comment by tiancaiamao** [comment]
Ping @winkyao @crazycs520

**Comment by winkyao** [comment]
Please remember to update parser version in TiDB go.mod to use this fixed.

**Pull request merged**
