### PR TITLE
parser,ast: support `alter table add partition partitions by  hash partitioned table` syntax

### PR DESCRIPTION
**Pull request by ciscoxll**
support `alter table  add partition partitions by  hash partitioned table` syntax.
```sql
CREATE TABLE employees (
    id INT NOT NULL,
    fname VARCHAR(30),
    lname VARCHAR(30),
    hired DATE NOT NULL DEFAULT '1970-01-01',
    separated DATE NOT NULL DEFAULT '9999-12-31',
    job_code INT,
    store_id INT
)
PARTITION BY HASH(store_id)
PARTITIONS 4;

alter table employees add partition partitions 8;

```

support `alter table coalesce partition by  hash partitioned table` syntax.
```sql
CREATE TABLE clients (
    id INT,
    fname VARCHAR(30),
    lname VARCHAR(30),
    signed DATE
)
PARTITION BY HASH( MONTH(signed) )
PARTITIONS 12;
ALTER TABLE clients COALESCE PARTITION 4;
```

### CODE REVIEW

**Comment by ciscoxll** [comment]
@tiancaiamao @kennytm PTAL

**Comment by tiancaiamao** [comment]
Will we support `alter table coalesce partition by hash` ?

**Comment by ciscoxll** [comment]
@tiancaiamao Temporarily support `syntax` first.

**Comment by ciscoxll** [comment]
@tiancaiamao @kennytm PTAL

**Comment by ciscoxll** [comment]
@tiancaiamao PTAL

**Comment by tiancaiamao** [comment]
Is there a link reference to the TiDB PR?
We should make sure the new change doesn't break TiDB at least. @ciscoxll

**Comment by tiancaiamao** [comment]
LGTM

**Pull request merged**
