### PR TITLE
Fix compatibility for `OnUpdate`, `OnDelete` and other clauses (#331, #392, #393) (#642)

### PR DESCRIPTION
**Pull request by eurekaka**
cherry-pick https://github.com/pingcap/parser/pull/642 to 3.1.6, since 3.1.6 has just rebased release-3.0 which needs this parser change.

### CODE REVIEW

**Comment by kennytm** [comment]
We shouldn't have a `release-3.1.6` branch, only `release-3.1` or `release-3.0` branch 🤔

**Comment by eurekaka** [comment]
release-3.1 would be deprecated soon, and release-3.1.6 is the replacement. @coocood please help illustrate the existence of release-3.1.6 here.

**Comment by kennytm** [comment]
> release-3.1 would be deprecated soon, and release-3.1.6 is the replacement

Then the branch name makes no sense since the next versions are 3.0.6 and 3.1.0.

**Comment by coocood** [comment]
@kennytm release-3.1.6 would be renamed to release-3.1 later

**Pull request merged**
