### PR TITLE
*: change default charset from utf8 to utf8mb4

### PR DESCRIPTION
**Pull request by winkyao**
Required for https://github.com/pingcap/tidb/pull/7965/

### CODE REVIEW

**Comment by winkyao** [comment]
@tiancaiamao PTAL

**Comment by kennytm** [comment]
Please regenerate `parser.go` since you've modified `parser.y`.

**Comment by gregwebs** [comment]
LGTM

**Comment by winkyao** [comment]
@kennytm PTAL

**Comment by kennytm** [comment]
LGTM

**Pull request merged**
